---
ids-classifier:
  training-dataset-folder: IDS2012
  training-data-filetype: json # csv or json
  feature-names:
    source-ip: source
    destination-ip: destination
    source-port: sourcePort
    destination-port: destinationPort
    protocol: protocolName
    label: Tag
...